### PR TITLE
added Cortex-M TrustZone control registers

### PR DESCRIPTION
**Pull request by grzonka**

### CODE REVIEW

**Comment by rhelmot** [comment]
Looks good to me. Let me know when you're ready to have it merged!

**Comment by grzonka** [comment]
It is ready to be merged. Thanks!

**Comment by rhelmot** [comment]
Looks like you have some lint failures to address:

```
LINT FAILURE: archinfo/arch_arm.py regressed to 9.48/9.54
... archinfo/arch_arm.py:459:0: C0303: Trailing whitespace (trailing-whitespace)
... archinfo/arch_arm.py:20:0: C0413: Import "from .arch import Arch, register_arch, Endness, Register" should be placed at the top of the module (wrong-import-position)
... archinfo/arch_arm.py:21:0: C0413: Import "from .tls import TLSArchInfo" should be placed at the top of the module (wrong-import-position)
... archinfo/arch_arm.py:42:0: C0115: Missing class docstring (missing-class-docstring)
... archinfo/arch_arm.py:49:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
... archinfo/arch_arm.py:354:0: C0115: Missing class docstring (missing-class-docstring)
... archinfo/arch_arm.py:359:0: C0115: Missing class docstring (missing-class-docstring)
... archinfo/arch_arm.py:537:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
```

You should fix the failures on the lines you touched. If you wanna be a cool cat you could fix all of them! :cat:

**Comment by grzonka** [comment]
I have addressed the linting issues :)

**Comment by rhelmot** [comment]
Thanks!

**Pull request merged**
