### PR TITLE
Argument registers and positions for AMD64

### PR DESCRIPTION
**Pull request by mattrepl**
Added argument register position info. Removed registers from argument_registers that are not used for passing arguments.

### CODE REVIEW

**Comment by ltfish** [comment]
I'm not against this PR. But a note to angr team: in the long run, we should encode all those information in `SimCC`.

**Comment by mattrepl** [comment]
Yeah, agreed on needing a better place for calling convention info. I needed argument register order for the hack-y variable recovery I've been working on. Speaking of, will take a look at what you're doing.

**Comment by zardus** [comment]
I think I screwed something up with git. I was trying to rebase this on master and now everything has exploded.

**Comment by zardus** [comment]
Ok. I think we have to abandon this PR and migrate to #11.

**Pull request closed without merging**
